name: Jest Tests

on:
  pull_request:
    branches:
      - master
      
jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Jest tests

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker build
        run: docker build -t thingsdb . -f ci/thingsdb.Dockerfile

      - name: Docker run
        run: |
          docker run --name thingsdb -d -p 9200:9200 -p 9001:9001 -p 7681:7681 thingsdb
          wget http://localhost:9001/healthy || exit 1

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: npm install
        run: npm ci

      - name: jest run test
        run: npm test
