name: Jest Tests

on:
  pull_request:
    branches:
      - master
      
jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Jest tests

    services:
      thingsdb:
        image: ghcr.io/thingsdb/node:latest
        env:
          THINGSDB_INIT: 1
          THINGSDB_LISTEN_CLIENT_PORT: 9200
          THINGSDB_HTTP_STATUS_PORT: 9001
          THINGSDB_WS_PORT: 9270
        ports:
          - 9200:9200
          - 9001:9001
          - 9270:9270
        options: >-
          --health-cmd "wget http://localhost:9001/healthy || exit 1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: npm install
        run: npm ci

      - name: jest run test
        run: npm run test
