name: Jest wss tests

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Jest wss tests

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker build
        run: docker build -t thingsdb . -f ci/wss.Dockerfile

      - name: Docker run
        run: |
          docker run --name thingsdb_wss -d -p 9270:9270 -p 9002:9002 thingsdb
          wget http://localhost:9002/healthy || exit 1

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: npm install
        run: npm ci

      - name: jest run test
        env:
          URL: 'wss://127.0.0.1:9270'
          NODE_TLS_REJECT_UNAUTHORIZED: 0
        run: npm run test
