name: Playwright Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    name: Run Playwright tests

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker build
        run: docker build -t thingsdb . -f ci/thingsdb.Dockerfile

      - name: Docker run
        run: |
          docker run --name thingsdb -d -p 9200:9200 -p 9001:9001 -p 7681:7681 thingsdb
          wget http://localhost:9001/healthy || exit 1

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - name: Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
