name: Playwright Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    name: Run Playwright tests
    container:
      image: mcr.microsoft.com/playwright:v1.43.0-jammy

    services:
      thingsdb:
        image: ghcr.io/thingsdb/node:latest
        env:
          THINGSDB_INIT: 1
          THINGSDB_LISTEN_CLIENT_PORT: 9200
          THINGSDB_HTTP_STATUS_PORT: 9001
          THINGSDB_WS_PORT: 9270
        ports:
          - 9200:9200
          - 9001:9001
          - 9270:9270
        options: >-
          --health-cmd "wget http://localhost:9001/healthy || exit 1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Run Playwright tests
        run: npm run playwright
        env:
          URL: 'ws://thingsdb:9270'
