name: CI

on:
  pull_request:
    branches:
      - master
      
jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Jest tests
    
    services:
      thingsdb:
        image: ghcr.io/thingsdb/node:latest
        env:
          THINGSDB_BIND_CLIENT_ADDR: 0.0.0.0
          THINGSDB_BIND_NODE_ADDR: 0.0.0.0
          THINGSDB_LISTEN_CLIENT_PORT: 9200
          THINGSDB_HTTP_STATUS_PORT: 9001
          THINGSDB_WS_PORT: 7681
        ports:
          - 9200:9200
          - 9001:9001
          - 7681:7681
        options: >-
           --health-cmd "wget http://localhost:9001/healthy || exit 1"
           
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: npm install
        run: npm ci

      - name: jest run test
        run: npm test
